baseURL = "https://pavolloffay.github.io/website/"
relativeURLs = false
languageCode = "en-us"
title = "Pavol Loffay"
theme = "light-hugo"

publishDir = "docs"

author = "Pavol Loffay"
copyright = "© Copyright 2016 John Doe"


[Params]
  description = "Describe your website"
  email = "john@example.org"
  github = "tblyler"
  twitter = "tonyblyler"
  linkedin = "johndoe"
  facebook = "johndoe"
  youtube = "johndoe"
  logo = "/images/logo.png"
